module.exports = {
  "BorderRadiusM": 4,
  "BorderRadiusS": 2,
  "ColorWhite": "#ffffffff",
  "ColorBlack": "#000000ff",
  "ColorSnow": "#f5f5f5ff",
  "ColorBlackOpac10": "rgba(0, 0, 0, 0.1)",
  "ColorWhiteOpac50": "rgba(255, 255, 255, 0.5)",
  "ColorSilver": "#ccccccff",
  "ColorNickel": "#555555ff",
  "ColorCoal": "#333333ff",
  "ColorJet": "#222222ff",
  "ColorMidnight": "#111111ff",
  "ColorSmoke": "#ebebebff",
  "ColorBlackOpac70": "#000000b3",
  "ColorLightBlue": "#66c7ffff",
  "ColorBlue": "#0274b6ff",
  "ColorDarkBlue": "#015483ff",
  "ColorLightPurple": "#c0a1ffff",
  "ColorPurple": "#8856cbff",
  "ColorDarkPurple": "#59348aff",
  "ColorLightRed": "#ff8585ff",
  "ColorRed": "#e10000ff",
  "ColorDarkRed": "#ba0000ff",
  "ColorLightGreen": "#90d889ff",
  "ColorGreen": "#0a8200ff",
  "ColorDarkGreen": "#064f00ff",
  "ColorLightYellow": "#ffecb1ff",
  "ColorYellow": "#ffcf3dff",
  "ColorDarkYellow": "#5b3d2fff",
  "ColorLightGold": "#9e855eff",
  "ColorGold": "#816d4dff",
  "ColorDarkGold": "#69583eff",
  "DjColorPrimary015": "#f0f9feff",
  "DjColorPrimary025": "#e2f3feff",
  "DjColorPrimary050": "#c0e8ffff",
  "DjColorPrimary075": "#66c7ffff",
  "DjColorPrimary085": "#54b4eeff",
  "DjColorPrimary100": "#3798d6ff",
  "DjColorPrimary200": "#278acaff",
  "DjColorPrimary300": "#147cbdff",
  "DjColorPrimary400": "#0274b6ff",
  "DjColorPrimary500": "#00639bff",
  "DjColorPrimary600": "#015483ff",
  "DjColorPrimary700": "#003353ff",
  "DjColorPrimary800": "#012841ff",
  "DjColorPrimary900": "#001d32ff",
  "DjColorSecondary015": "#f9f7ffff",
  "DjColorSecondary025": "#f3eefeff",
  "DjColorSecondary050": "#e7defeff",
  "DjColorSecondary075": "#d2bbffff",
  "DjColorSecondary085": "#c0a1ffff",
  "DjColorSecondary100": "#a47de6ff",
  "DjColorSecondary200": "#996ddbff",
  "DjColorSecondary300": "#8d5ed0ff",
  "DjColorSecondary400": "#8856cbff",
  "DjColorSecondary500": "#7347aeff",
  "DjColorSecondary600": "#59348aff",
  "DjColorSecondary700": "#3d2162ff",
  "DjColorSecondary800": "#301a4dff",
  "DjColorSecondary900": "#24123bff",
  "DjColorTertiary015": "#faf8f5ff",
  "DjColorTertiary025": "#f4f0ebff",
  "DjColorTertiary050": "#e8e2d9ff",
  "DjColorTertiary075": "#d2c5b3ff",
  "DjColorTertiary085": "#bba98eff",
  "DjColorTertiary100": "#a58d69ff",
  "DjColorTertiary200": "#9e855eff",
  "DjColorTertiary300": "#887351ff",
  "DjColorTertiary400": "#816d4dff",
  "DjColorTertiary500": "#69583eff",
  "DjColorTertiary600": "#534530ff",
  "DjColorTertiary700": "#392f1fff",
  "DjColorTertiary800": "#2d2418ff",
  "DjColorTertiary900": "#211b10ff",
  "DjColorPositive015": "#f6f8f5ff",
  "DjColorPositive025": "#edf2ecff",
  "DjColorPositive050": "#cdeac9ff",
  "DjColorPositive075": "#90d889ff",
  "DjColorPositive085": "#51c648ff",
  "DjColorPositive100": "#35a62dff",
  "DjColorPositive200": "#27981fff",
  "DjColorPositive300": "#19890eff",
  "DjColorPositive400": "#0a8200ff",
  "DjColorPositive500": "#096e00ff",
  "DjColorPositive600": "#064f00ff",
  "DjColorPositive700": "#043902ff",
  "DjColorPositive800": "#022d00ff",
  "DjColorPositive900": "#002200ff",
  "DjColorNegative015": "#fff6f5ff",
  "DjColorNegative025": "#ffecebff",
  "DjColorNegative050": "#fedad8ff",
  "DjColorNegative075": "#ffb3b1ff",
  "DjColorNegative085": "#ff8585ff",
  "DjColorNegative100": "#f35f5aff",
  "DjColorNegative200": "#ed4740ff",
  "DjColorNegative300": "#e5261fff",
  "DjColorNegative400": "#e10000ff",
  "DjColorNegative500": "#ba0000ff",
  "DjColorNegative600": "#930201ff",
  "DjColorNegative700": "#690000ff",
  "DjColorNegative800": "#540202ff",
  "DjColorNegative900": "#410000ff",
  "DjColorHighlight015": "#fff8e3ff",
  "DjColorHighlight025": "#ffecb1ff",
  "DjColorHighlight050": "#fee08cff",
  "DjColorHighlight075": "#ffcf3dff",
  "DjColorHighlight085": "#d0a53dff",
  "DjColorHighlight100": "#b28b3eff",
  "DjColorHighlight200": "#a37d3dff",
  "DjColorHighlight300": "#94703aff",
  "DjColorHighlight400": "#876438ff",
  "DjColorHighlight500": "#795836ff",
  "DjColorHighlight600": "#5b3d2fff",
  "DjColorHighlight700": "#412b20ff",
  "DjColorHighlight800": "#342118ff",
  "DjColorHighlight900": "#271810ff",
  "DjColorInfo015": "#f3f8ffff",
  "DjColorInfo025": "#e8f2ffff",
  "DjColorInfo050": "#d3e4feff",
  "DjColorInfo075": "#a6c8ffff",
  "DjColorInfo085": "#7babffff",
  "DjColorInfo100": "#518dffff",
  "DjColorInfo200": "#3a7efdff",
  "DjColorInfo300": "#206cffff",
  "DjColorInfo400": "#0f62feff",
  "DjColorInfo500": "#0353daff",
  "DjColorInfo600": "#093ea6ff",
  "DjColorInfo700": "#012979ff",
  "DjColorInfo800": "#05205fff",
  "DjColorInfo900": "#01174bff",
  "DjColorSystem015": "#f3f9ffff",
  "DjColorSystem025": "#e5f2ffff",
  "DjColorSystem050": "#cfe4ffff",
  "DjColorSystem075": "#a0c9ffff",
  "DjColorSystem085": "#70adffff",
  "DjColorSystem100": "#3e90fdff",
  "DjColorSystem200": "#007affff",
  "DjColorSystem300": "#0472eeff",
  "DjColorSystem400": "#0a66d8ff",
  "DjColorSystem500": "#005bc0ff",
  "DjColorSystem600": "#034493ff",
  "DjColorSystem700": "#032e68ff",
  "DjColorSystem800": "#002456ff",
  "DjColorSystem900": "#011a41ff",
  "DjColorNeutral015": "#f5f5f5ff",
  "DjColorNeutral025": "#ebebebff",
  "DjColorNeutral050": "#e2e2e2ff",
  "DjColorNeutral075": "#ccccccff",
  "DjColorNeutral085": "#abababff",
  "DjColorNeutral100": "#919191ff",
  "DjColorNeutral200": "#848484ff",
  "DjColorNeutral300": "#767676ff",
  "DjColorNeutral400": "#6f6f6fff",
  "DjColorNeutral500": "#555555ff",
  "DjColorNeutral600": "#333333ff",
  "DjColorNeutral700": "#222222ff",
  "DjColorNeutral800": "#1b1b1bff",
  "DjColorNeutral900": "#111111ff",
  "DjColorBlack": "#000000ff",
  "DjColorWhite": "#ffffffff",
  "DjColorBlack05a": "#0000000d",
  "DjColorBlack10a": "#0000001a",
  "DjColorBlack20a": "#00000033",
  "DjColorBlack30a": "#0000004d",
  "DjColorBlack40a": "#00000066",
  "DjColorBlack50a": "#00000080",
  "DjColorBlack60a": "#00000099",
  "DjColorBlack70a": "#000000b3",
  "DjColorBlack80a": "#000000cc",
  "DjColorBlack90a": "#000000e6",
  "DjColorBlack95a": "#000000f2",
  "DjColorWhite05a": "#ffffff0d",
  "DjColorWhite10a": "#ffffff1a",
  "DjColorWhite20a": "#ffffff33",
  "DjColorWhite30a": "#ffffff4d",
  "DjColorWhite40a": "#ffffff66",
  "DjColorWhite50a": "#ffffff80",
  "DjColorWhite60a": "#ffffff99",
  "DjColorWhite70a": "#ffffffb3",
  "DjColorWhite80a": "#ffffffcc",
  "DjColorWhite90a": "#ffffffe6",
  "DjColorWhite95a": "#fffffff2",
  "ElevationCardX": "0",
  "ElevationCardY": "1",
  "ElevationCardBlur": "2",
  "ElevationCardSpread": "1",
  "ElevationCardColorLight": "rgba(0, 0, 0, 0.1)",
  "ElevationCardColorDark": "rgba(255, 255, 255, 0.5)",
  "ElevationDropdownX": "0",
  "ElevationDropdownY": "3",
  "ElevationDropdownBlur": "7",
  "ElevationDropdownSpread": "-4",
  "ElevationDropdownColorLight": "rgba(0, 0, 0, 0.1)",
  "ElevationDropdownColorDark": "rgba(255, 255, 255, 0.5)",
  "FontFamilyRetina": "Retina",
  "FontFamilyExchange": "Exchange",
  "FontFamilyEscrowCondensed": "Escrow Condensed",
  "FontFamilyRetinaNarrow": "Retina Narrow",
  "FontFamilyRetinaWide": "Retina Wide",
  "FontFamilyHelvetica": "Helvetica",
  "FontFamilyArial": "Arial",
  "FontFamilyEscrowBanner": "Escrow Banner",
  "FontFamilyGeorgia": "Georgia",
  "FontFamilySerif": "serif",
  "FontFamilySansSerif": "sans-serif",
  "FontWeightThin": 100,
  "FontWeightExtraLight": 200,
  "FontWeightLight": 300,
  "FontWeightRegular": 400,
  "FontWeightMedium": 500,
  "FontWeightSemiBold": 600,
  "FontWeightBold": 700,
  "FontWeightExtraBold": 800,
  "FontWeightUltraBold": 900,
  "FontStyleNormal": "normal",
  "FontStyleItalic": "italic",
  "FontCaseSentence": "sentence",
  "FontCaseUppercase": "uppercase",
  "FontLetterSpacing1": 1,
  "FontLetterSpacing05": 0.5,
  "FontLetterSpacing08": 0.8,
  "FontFontStackEscrowBanner": "Escrow Banner, Georgia, serif",
  "FontFontStackEscrowCondensed": "Escrow Condensed, Georgia, serif",
  "FontFontStackExchange": "Exchange, Georgia, serif",
  "FontFontStackRetina": "Retina, Helvetica, Arial, sans-serif",
  "FontFontStackRetinaNarrow": "Retina Narrow, Helvetica, Arial, sans-serif",
  "FontFontStackRetinaWide": "Retina Wide, Helvetica, Arial,sans-serif",
  "FontTextTransformSentence": "capitalize",
  "FontTextTransformUppercase": "uppercase",
  "SpacingSpacer48": 48,
  "SpacingSpacer36": 36,
  "SpacingSpacer32": 32,
  "SpacingSpacer24": 24,
  "SpacingSpacer20": 20,
  "SpacingSpacer16": 16,
  "SpacingSpacer12": 12,
  "SpacingSpacer8": 8,
  "SpacingSpacer4": 4,
  "TypographyBodyFontSizeM": 17,
  "TypographyBodyFontSizeS": 15,
  "TypographyBodyFontLineHeightM": 28,
  "TypographyBodyFontLineHeightS": 24,
  "TypographyBodyStandardMFontSize": 17,
  "TypographyBodyStandardMLineHeight": 28,
  "TypographyBodyStandardMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyBodyStandardMFontWeight": 400,
  "TypographyBodySerifMFontSize": 17,
  "TypographyBodySerifMLineHeight": 28,
  "TypographyBodySerifMFontFamily": "Exchange, Georgia, serif",
  "TypographyBodySerifMFontWeight": 400,
  "TypographyBodySerifSFontSize": 15,
  "TypographyBodySerifSLineHeight": 24,
  "TypographyBodySerifSFontFamily": "Exchange",
  "TypographyBodySerifSFontWeight": 400,
  "TypographyBylineFontSizeM": 17,
  "TypographyBylineFontSizeS": 14,
  "TypographyBylineFontLineHeightM": 28,
  "TypographyBylineFontLineHeightS": 20,
  "TypographyBylineStandardMFontSize": 17,
  "TypographyBylineStandardMLineHeight": 28,
  "TypographyBylineStandardMFontFamily": "Exchange, Georgia, serif",
  "TypographyBylineStandardMFontWeight": 400,
  "TypographyBylineStandardMFontStyle": "italic",
  "TypographyBylineStandardSFontSize": 14,
  "TypographyBylineStandardSLineHeight": 20,
  "TypographyBylineStandardSFontFamily": "Exchange",
  "TypographyBylineStandardSFontWeight": 400,
  "TypographyBylineStandardSFontStyle": "italic",
  "TypographyCaptionFontSizeM": 14,
  "TypographyCaptionFontSizeS": 13,
  "TypographyCaptionFontLineHeightM": 20,
  "TypographyCaptionStandardMFontSize": 14,
  "TypographyCaptionStandardMLineHeight": 20,
  "TypographyCaptionStandardMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyCaptionStandardMFontWeight": 300,
  "TypographyCaptionStandardSFontSize": 13,
  "TypographyCaptionStandardSLineHeight": 20,
  "TypographyCaptionStandardSFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyCaptionStandardSFontWeight": 300,
  "TypographyFlashlineFontSizeM": 13,
  "TypographyFlashlineFontLineHeightM": 16,
  "TypographyFlashlineStandardMFontSize": 13,
  "TypographyFlashlineStandardMLineHeight": 16,
  "TypographyFlashlineStandardMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyFlashlineStandardMFontWeight": 500,
  "TypographyFlashlineStandardMLetterSpacing": 0.8,
  "TypographyFlashlineStandardMCase": "uppercase",
  "TypographyFlashlineStandardMTextTransform": "uppercase",
  "TypographyFlashlineOpinionMFontSize": 13,
  "TypographyFlashlineOpinionMLineHeight": 16,
  "TypographyFlashlineOpinionMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyFlashlineOpinionMFontWeight": 500,
  "TypographyFlashlineOpinionMLetterSpacing": 0.8,
  "TypographyFlashlineOpinionMCase": "uppercase",
  "TypographyFlashlineOpinionMTextTransform": "uppercase",
  "TypographyFlashlinePriorityMFontSize": 13,
  "TypographyFlashlinePriorityMLineHeight": 16,
  "TypographyFlashlinePriorityMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyFlashlinePriorityMFontWeight": 500,
  "TypographyFlashlinePriorityMLetterSpacing": 0.8,
  "TypographyFlashlinePriorityMCase": "uppercase",
  "TypographyFlashlinePriorityMTextTransform": "uppercase",
  "TypographyFlashlineMagazineMFontSize": 13,
  "TypographyFlashlineMagazineMLineHeight": 16,
  "TypographyFlashlineMagazineMFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyFlashlineMagazineMFontWeight": 300,
  "TypographyFlashlineMagazineMLetterSpacing": 1,
  "TypographyFlashlineMagazineMCase": "uppercase",
  "TypographyFlashlineMagazineMTextTransform": "uppercase",
  "TypographyHeadlineFontSizeXxl": 40,
  "TypographyHeadlineFontSizeXl": 36,
  "TypographyHeadlineFontSizeL": 32,
  "TypographyHeadlineFontSizeM": 28,
  "TypographyHeadlineFontSizeS": 22,
  "TypographyHeadlineFontSizeXs": 18,
  "TypographyHeadlineFontSizeXxs": 16,
  "TypographyHeadlineFontLineHeightXxl": 40,
  "TypographyHeadlineFontLineHeightXl": 36,
  "TypographyHeadlineFontLineHeightL": 36,
  "TypographyHeadlineFontLineHeightM": 32,
  "TypographyHeadlineFontLineHeightS": 24,
  "TypographyHeadlineFontLineHeightXs": 20,
  "TypographyHeadlineFontLineHeightXxs": 24,
  "TypographyHeadlineStandardXxlFontSize": 40,
  "TypographyHeadlineStandardXxlLineHeight": 40,
  "TypographyHeadlineStandardXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardXxlFontWeight": 700,
  "TypographyHeadlineStandardXxlTextTransform": "capitalize",
  "TypographyHeadlineStandardXlFontSize": 36,
  "TypographyHeadlineStandardXlLineHeight": 36,
  "TypographyHeadlineStandardXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardXlFontWeight": 700,
  "TypographyHeadlineStandardXlTextTransform": "capitalize",
  "TypographyHeadlineStandardLFontSize": 32,
  "TypographyHeadlineStandardLLineHeight": 36,
  "TypographyHeadlineStandardLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardLFontWeight": 700,
  "TypographyHeadlineStandardLTextTransform": "capitalize",
  "TypographyHeadlineStandardMFontSize": 28,
  "TypographyHeadlineStandardMLineHeight": 32,
  "TypographyHeadlineStandardMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardMFontWeight": 700,
  "TypographyHeadlineStandardMTextTransform": "capitalize",
  "TypographyHeadlineStandardSFontSize": 22,
  "TypographyHeadlineStandardSLineHeight": 24,
  "TypographyHeadlineStandardSFontFamily": "Escrow Condensed",
  "TypographyHeadlineStandardSFontWeight": 700,
  "TypographyHeadlineStandardXsFontSize": 18,
  "TypographyHeadlineStandardXsLineHeight": 20,
  "TypographyHeadlineStandardXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardXsFontWeight": 700,
  "TypographyHeadlineStandardXsTextTransform": "capitalize",
  "TypographyHeadlineStandardXxsFontSize": 16,
  "TypographyHeadlineStandardXxsLineHeight": 24,
  "TypographyHeadlineStandardXxsFontFamily": "Exchange, Georgia, serif",
  "TypographyHeadlineStandardXxsFontWeight": 500,
  "TypographyHeadlineStandardXxsTextTransform": "capitalize",
  "TypographyHeadlineOpinionXxlFontSize": 40,
  "TypographyHeadlineOpinionXxlLineHeight": 40,
  "TypographyHeadlineOpinionXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXxlFontStyle": "italic",
  "TypographyHeadlineOpinionXxlFontWeight": 400,
  "TypographyHeadlineOpinionXxlTextTransform": "capitalize",
  "TypographyHeadlineOpinionXlFontSize": 36,
  "TypographyHeadlineOpinionXlLineHeight": 36,
  "TypographyHeadlineOpinionXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXlFontStyle": "italic",
  "TypographyHeadlineOpinionXlFontWeight": 400,
  "TypographyHeadlineOpinionXlTextTransform": "capitalize",
  "TypographyHeadlineOpinionLFontSize": 32,
  "TypographyHeadlineOpinionLLineHeight": 36,
  "TypographyHeadlineOpinionLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionLFontStyle": "italic",
  "TypographyHeadlineOpinionLFontWeight": 400,
  "TypographyHeadlineOpinionLTextTransform": "capitalize",
  "TypographyHeadlineOpinionMFontSize": 28,
  "TypographyHeadlineOpinionMLineHeight": 32,
  "TypographyHeadlineOpinionMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionMFontStyle": "italic",
  "TypographyHeadlineOpinionMFontWeight": 400,
  "TypographyHeadlineOpinionMTextTransform": "capitalize",
  "TypographyHeadlineOpinionSFontSize": 22,
  "TypographyHeadlineOpinionSLineHeight": 24,
  "TypographyHeadlineOpinionSFontFamily": "Escrow Condensed",
  "TypographyHeadlineOpinionSFontStyle": "italic",
  "TypographyHeadlineOpinionSFontWeight": 400,
  "TypographyHeadlineOpinionXsFontSize": 18,
  "TypographyHeadlineOpinionXsLineHeight": 20,
  "TypographyHeadlineOpinionXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXsFontStyle": "italic",
  "TypographyHeadlineOpinionXsFontWeight": 400,
  "TypographyHeadlineOpinionXsTextTransform": "capitalize",
  "TypographyHeadlineOpinionXxsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXxsTextTransform": "capitalize",
  "TypographyHeadlineFeaturesXxlFontSize": 40,
  "TypographyHeadlineFeaturesXxlLineHeight": 40,
  "TypographyHeadlineFeaturesXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXxlFontWeight": 400,
  "TypographyHeadlineFeaturesXxlTextTransform": "capitalize",
  "TypographyHeadlineFeaturesXlFontSize": 36,
  "TypographyHeadlineFeaturesXlLineHeight": 36,
  "TypographyHeadlineFeaturesXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXlFontWeight": 400,
  "TypographyHeadlineFeaturesXlTextTransform": "capitalize",
  "TypographyHeadlineFeaturesLFontSize": 32,
  "TypographyHeadlineFeaturesLLineHeight": 36,
  "TypographyHeadlineFeaturesLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesLFontWeight": 400,
  "TypographyHeadlineFeaturesLTextTransform": "capitalize",
  "TypographyHeadlineFeaturesMFontSize": 28,
  "TypographyHeadlineFeaturesMLineHeight": 32,
  "TypographyHeadlineFeaturesMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesMFontWeight": 400,
  "TypographyHeadlineFeaturesMTextTransform": "capitalize",
  "TypographyHeadlineFeaturesSFontSize": 22,
  "TypographyHeadlineFeaturesSLineHeight": 24,
  "TypographyHeadlineFeaturesSFontFamily": "Escrow Condensed",
  "TypographyHeadlineFeaturesSFontWeight": 400,
  "TypographyHeadlineFeaturesXsFontSize": 18,
  "TypographyHeadlineFeaturesXsLineHeight": 20,
  "TypographyHeadlineFeaturesXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXsFontWeight": 400,
  "TypographyHeadlineFeaturesXsTextTransform": "capitalize",
  "TypographyHeadlineFeaturesXxsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXxsTextTransform": "capitalize",
  "TypographyHeadlineMagazineXxlFontSize": 40,
  "TypographyHeadlineMagazineXxlLineHeight": 40,
  "TypographyHeadlineMagazineXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXxlFontWeight": 300,
  "TypographyHeadlineMagazineXxlTextTransform": "capitalize",
  "TypographyHeadlineMagazineXlFontSize": 36,
  "TypographyHeadlineMagazineXlLineHeight": 36,
  "TypographyHeadlineMagazineXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXlFontWeight": 300,
  "TypographyHeadlineMagazineXlTextTransform": "capitalize",
  "TypographyHeadlineMagazineLFontSize": 32,
  "TypographyHeadlineMagazineLLineHeight": 36,
  "TypographyHeadlineMagazineLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineLFontWeight": 300,
  "TypographyHeadlineMagazineLTextTransform": "capitalize",
  "TypographyHeadlineMagazineMFontSize": 28,
  "TypographyHeadlineMagazineMLineHeight": 32,
  "TypographyHeadlineMagazineMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineMFontWeight": 300,
  "TypographyHeadlineMagazineMTextTransform": "capitalize",
  "TypographyHeadlineMagazineSFontSize": 22,
  "TypographyHeadlineMagazineSLineHeight": 24,
  "TypographyHeadlineMagazineSFontFamily": "Escrow Condensed",
  "TypographyHeadlineMagazineSFontWeight": 300,
  "TypographyHeadlineMagazineXsFontSize": 18,
  "TypographyHeadlineMagazineXsLineHeight": 20,
  "TypographyHeadlineMagazineXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXsFontWeight": 300,
  "TypographyHeadlineMagazineXsTextTransform": "capitalize",
  "TypographyHeadlineMagazineXxsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXxsTextTransform": "capitalize",
  "TypographyHeadlineOffplatformXxlFontSize": 32,
  "TypographyHeadlineOffplatformXxlLineHeight": 36,
  "TypographyHeadlineOffplatformXxlFontFamily": "Retina",
  "TypographyHeadlineOffplatformXxlFontWeight": 500,
  "TypographyStrapFontSizeM": 18,
  "TypographyStrapFontSizeS": 16,
  "TypographyStrapFontLineHeightM": 24,
  "TypographyStrapFontLineHeightS": 24,
  "TypographyStrapStandardMFontSize": 18,
  "TypographyStrapStandardMLineHeight": 24,
  "TypographyStrapStandardMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyStrapStandardMFontWeight": 500,
  "TypographyStrapStandardMTextTransform": "uppercase",
  "TypographyStrapStandardSFontSize": 16,
  "TypographyStrapStandardSLineHeight": 24,
  "TypographyStrapStandardSFontFamily": "Retina",
  "TypographyStrapStandardSFontWeight": 500,
  "TypographyStrapOpinionMFontSize": 18,
  "TypographyStrapOpinionMLineHeight": 24,
  "TypographyStrapOpinionMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyStrapOpinionMFontWeight": 500,
  "TypographyStrapOpinionMTextTransform": "uppercase",
  "TypographyStrapPriorityMFontSize": 18,
  "TypographyStrapPriorityMLineHeight": 24,
  "TypographyStrapPriorityMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyStrapPriorityMFontWeight": 500,
  "TypographyStrapPriorityMTextTransform": "uppercase",
  "TypographyStrapMagazineMFontSize": 16,
  "TypographyStrapMagazineMLineHeight": 24,
  "TypographyStrapMagazineMFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyStrapMagazineMFontWeight": 300,
  "TypographyStrapMagazineMTextTransform": "uppercase",
  "TypographyStrapLinkFontSizeS": 16,
  "TypographyStrapLinkFontLineHeightS": 24,
  "TypographyStrapLinkStandardSFontSize": 16,
  "TypographyStrapLinkStandardSLineHeight": 24,
  "TypographyStrapLinkStandardSFontFamily": "Retina",
  "TypographyStrapLinkStandardSFontWeight": 300,
  "TypographySubheadingFontSizeM": 20,
  "TypographySubheadingFontSizeS": 17,
  "TypographySubheadingFontLineHeightM": 28,
  "TypographySubheadingFontLineHeightS": 24,
  "TypographySubheadingStandardMFontSize": 20,
  "TypographySubheadingStandardMLineHeight": 28,
  "TypographySubheadingStandardMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographySubheadingStandardMFontWeight": 300,
  "TypographySubheadingStandardMTextTransform": "capitalize",
  "TypographySubheadingStandardSFontSize": 17,
  "TypographySubheadingStandardSLineHeight": 24,
  "TypographySubheadingStandardSFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographySubheadingStandardSFontWeight": 300,
  "TypographySubheadingStandardSTextTransform": "capitalize",
  "TypographySubheadingSerifMFontSize": 20,
  "TypographySubheadingSerifMLineHeight": 28,
  "TypographySubheadingSerifMFontFamily": "Exchange, Georgia, serif",
  "TypographySubheadingSerifMFontWeight": 400,
  "TypographySubheadingSerifSFontSize": 17,
  "TypographySubheadingSerifSLineHeight": 24,
  "TypographySubheadingSerifSFontFamily": "Exchange, Georgia, serif",
  "TypographySubheadingSerifSFontWeight": 400,
  "TypographySummaryFontSizeM": 16,
  "TypographySummaryFontSizeS": 14,
  "TypographySummaryFontLineHeightM": 24,
  "TypographySummaryFontLineHeightS": 20,
  "TypographySummaryStandardMFontSize": 16,
  "TypographySummaryStandardMLineHeight": 24,
  "TypographySummaryStandardMFontFamily": "Exchange, Georgia, serif",
  "TypographySummaryStandardMFontWeight": 400,
  "TypographySummaryStandardSFontSize": 14,
  "TypographySummaryStandardSLineHeight": 20,
  "TypographySummaryStandardSFontFamily": "Exchange, Georgia, serif",
  "TypographySummaryStandardSFontWeight": 400,
  "TypographyTimestampFontSizeM": 14,
  "TypographyTimestampFontSizeS": 13,
  "TypographyTimestampFontSizeXs": 13,
  "TypographyTimestampFontLineHeightM": 16,
  "TypographyTimestampFontLineHeightXs": 16,
  "TypographyTimestampStandardXsFontSize": 13,
  "TypographyTimestampStandardXsLineHeight": 16,
  "TypographyTimestampStandardXsFontFamily": "Retina",
  "TypographyTimestampStandardXsFontWeight": 300,
  "TypographyTimestampStandardMFontSize": 14,
  "TypographyTimestampStandardMLineHeight": 16,
  "TypographyTimestampStandardMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyTimestampStandardMFontWeight": 400,
  "TypographyTimestampStandardMTextTransform": "uppercase",
  "TypographyTimestampStandardSFontSize": 13,
  "TypographyTimestampStandardSLineHeight": 16,
  "TypographyTimestampStandardSFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyTimestampStandardSFontWeight": 400,
  "TypographyTimestampStandardSTextTransform": "uppercase",
  "TypographySansSerifFontSizeStandardL": 18,
  "TypographySansSerifFontSizeStandardM": 16,
  "TypographySansSerifFontSizeStandardS": 14,
  "TypographySansSerifFontSizeStandardXs": 13,
  "TypographySansSerifFontSizeStandardXxs": 12,
  "TypographySansSerifFontSizeStandardXxxs": 10,
  "TypographySansSerifFontSizeCondensedXxl": 24,
  "TypographySansSerifFontSizeCondensedXl": 20,
  "TypographySansSerifFontSizeCondensedL": 18,
  "TypographySansSerifFontSizeCondensedM": 16,
  "TypographySansSerifFontSizeCapsTitleStandardL": 28,
  "TypographySansSerifFontSizeCapsTitleStandardM": 18,
  "TypographySansSerifFontSizeCapsTitleStandardS": 13,
  "TypographySansSerifFontSizeCapsTitleMagazineM": 16,
  "TypographySansSerifFontSizeCapsTitleMagazineS": 12,
  "TypographySansSerifFontLineHeightStandardL": 24,
  "TypographySansSerifFontLineHeightStandardM": 24,
  "TypographySansSerifFontLineHeightStandardS": 20,
  "TypographySansSerifFontLineHeightStandardXs": 16,
  "TypographySansSerifFontLineHeightStandardXxs": 16,
  "TypographySansSerifFontLineHeightStandardXxxs": 14,
  "TypographySansSerifFontLineHeightCondensedXxl": 28,
  "TypographySansSerifFontLineHeightCondensedXl": 24,
  "TypographySansSerifFontLineHeightCondensedL": 24,
  "TypographySansSerifFontLineHeightCondensedM": 20,
  "TypographySansSerifFontLineHeightCapsTitleStandardL": 32,
  "TypographySansSerifFontLineHeightCapsTitleStandardM": 24,
  "TypographySansSerifFontLineHeightCapsTitleStandardS": 16,
  "TypographySansSerifFontLineHeightCapsTitleMagazineM": 14,
  "TypographySansSerifFontLineHeightCapsTitleMagazineS": 16,
  "TypographySansSerifStandardLThickFontSize": 18,
  "TypographySansSerifStandardLThickLineHeight": 24,
  "TypographySansSerifStandardLThickFontFamily": "Retina",
  "TypographySansSerifStandardLThickFontWeight": 500,
  "TypographySansSerifStandardLThinFontSize": 18,
  "TypographySansSerifStandardLThinLineHeight": 24,
  "TypographySansSerifStandardLThinFontFamily": "Retina",
  "TypographySansSerifStandardLThinFontWeight": 300,
  "TypographySansSerifStandardMThickFontSize": 16,
  "TypographySansSerifStandardMThickLineHeight": 24,
  "TypographySansSerifStandardMThickFontFamily": "Retina",
  "TypographySansSerifStandardMThickFontWeight": 500,
  "TypographySansSerifStandardMThinFontSize": 16,
  "TypographySansSerifStandardMThinLineHeight": 24,
  "TypographySansSerifStandardMThinFontFamily": "Retina",
  "TypographySansSerifStandardMThinFontWeight": 300,
  "TypographySansSerifStandardSThickFontSize": 14,
  "TypographySansSerifStandardSThickLineHeight": 20,
  "TypographySansSerifStandardSThickFontFamily": "Retina",
  "TypographySansSerifStandardSThickFontWeight": 500,
  "TypographySansSerifStandardSThinFontSize": 14,
  "TypographySansSerifStandardSThinLineHeight": 20,
  "TypographySansSerifStandardSThinFontFamily": "Retina",
  "TypographySansSerifStandardSThinFontWeight": 300,
  "TypographySansSerifStandardXsThickFontSize": 13,
  "TypographySansSerifStandardXsThickLineHeight": 16,
  "TypographySansSerifStandardXsThickFontFamily": "Retina",
  "TypographySansSerifStandardXsThickFontWeight": 500,
  "TypographySansSerifStandardXsThinFontSize": 13,
  "TypographySansSerifStandardXsThinLineHeight": 16,
  "TypographySansSerifStandardXsThinFontFamily": "Retina",
  "TypographySansSerifStandardXsThinFontWeight": 300,
  "TypographySansSerifStandardXxsThickFontSize": 12,
  "TypographySansSerifStandardXxsThickLineHeight": 16,
  "TypographySansSerifStandardXxsThickFontFamily": "Retina",
  "TypographySansSerifStandardXxsThickFontWeight": 500,
  "TypographySansSerifStandardXxsThinFontSize": 12,
  "TypographySansSerifStandardXxsThinLineHeight": 16,
  "TypographySansSerifStandardXxsThinFontFamily": "Retina",
  "TypographySansSerifStandardXxsThinFontWeight": 300,
  "TypographySansSerifStandardXxxsThickFontSize": 10,
  "TypographySansSerifStandardXxxsThickLineHeight": 14,
  "TypographySansSerifStandardXxxsThickFontFamily": "Retina",
  "TypographySansSerifStandardXxxsThickFontWeight": 500,
  "TypographySansSerifStandardXxxsThinFontSize": 10,
  "TypographySansSerifStandardXxxsThinLineHeight": 14,
  "TypographySansSerifStandardXxxsThinFontFamily": "Retina",
  "TypographySansSerifStandardXxxsThinFontWeight": 300,
  "TypographySansSerifCondensedXxlThickFontSize": 24,
  "TypographySansSerifCondensedXxlThickLineHeight": 28,
  "TypographySansSerifCondensedXxlThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedXxlThickFontWeight": 500,
  "TypographySansSerifCondensedXlThickFontSize": 20,
  "TypographySansSerifCondensedXlThickLineHeight": 24,
  "TypographySansSerifCondensedXlThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedXlThickFontWeight": 500,
  "TypographySansSerifCondensedLThickFontSize": 18,
  "TypographySansSerifCondensedLThickLineHeight": 24,
  "TypographySansSerifCondensedLThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedLThickFontWeight": 500,
  "TypographySansSerifCondensedMThickFontSize": 16,
  "TypographySansSerifCondensedMThickLineHeight": 20,
  "TypographySansSerifCondensedMThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedMThickFontWeight": 500,
  "TypographySansSerifCapsTitleLStandardFontSize": 28,
  "TypographySansSerifCapsTitleLStandardLineHeight": 32,
  "TypographySansSerifCapsTitleLStandardFontFamily": "Retina Narrow",
  "TypographySansSerifCapsTitleLStandardFontWeight": 700,
  "TypographySansSerifCapsTitleLStandardFontCase": "uppercase",
  "TypographySansSerifCapsTitleMStandardFontSize": 18,
  "TypographySansSerifCapsTitleMStandardLineHeight": 24,
  "TypographySansSerifCapsTitleMStandardFontFamily": "Retina Narrow",
  "TypographySansSerifCapsTitleMStandardFontWeight": 500,
  "TypographySansSerifCapsTitleMStandardFontCase": "uppercase",
  "TypographySansSerifCapsTitleMMagazineFontSize": 16,
  "TypographySansSerifCapsTitleMMagazineLineHeight": 14,
  "TypographySansSerifCapsTitleMMagazineFontFamily": "Retina Wide",
  "TypographySansSerifCapsTitleMMagazineFontWeight": 300,
  "TypographySansSerifCapsTitleMMagazineFontCase": "uppercase",
  "TypographySansSerifCapsTitleSStandardFontSize": 13,
  "TypographySansSerifCapsTitleSStandardLineHeight": 16,
  "TypographySansSerifCapsTitleSStandardFontFamily": "Retina Narrow",
  "TypographySansSerifCapsTitleSStandardFontWeight": 500,
  "TypographySansSerifCapsTitleSStandardFontCase": "uppercase",
  "TypographySansSerifCapsTitleSStandardFontLetterSpacing": 0.8,
  "TypographySansSerifCapsTitleSMagazineFontSize": 16,
  "TypographySansSerifCapsTitleSMagazineLineHeight": 14,
  "TypographySansSerifCapsTitleSMagazineFontFamily": "Retina Wide",
  "TypographySansSerifCapsTitleSMagazineFontWeight": 300,
  "TypographySansSerifCapsTitleSMagazineFontCase": "uppercase",
  "TypographySansSerifCapsTitleSMagazineFontLetterSpacing": 1,
  "BoxShadowCardDark": "0px 1px 2px 1px rgba(255, 255, 255, 0.5)",
  "BoxShadowCardLight": "0px 1px 2px 1px rgba(0, 0, 0, 0.1)",
  "BoxShadowDropdownDark": "0px 3px 7px -4px rgba(255, 255, 255, 0.5)",
  "BoxShadowDropdownLight": "0px 3px 7px -4px rgba(0, 0, 0, 0.1)"
}