module.exports = {
  "BorderRadiusM": 4,
  "BorderRadiusS": 2,
  "ColorWhite": "#ffffff",
  "ColorBlack": "#000000",
  "ColorSnow": "#f5f5f5",
  "ColorBlackOpac10": "rgba(0, 0, 0, 0.1)",
  "ColorWhiteOpac50": "rgba(255, 255, 255, 0.5)",
  "ColorPaper400": "#ffffff",
  "ColorPaper600": "#f5f5f5",
  "ColorPaper800": "#ebebeb",
  "ColorTextButtonNeutralDefault": "#cccccc",
  "ColorTextButtonNeutralHover": "#cccccc",
  "ColorTextButtonNeutralActive": "#cccccc",
  "ColorTextButtonNeutralDisabled": "#cccccc",
  "ColorTextButtonSystemDefault": "#cccccc",
  "ColorTextButtonSystemHover": "#cccccc",
  "ColorTextButtonSystemActive": "#cccccc",
  "ColorTextButtonSystemDisabled": "#cccccc",
  "ColorTextButtonInfoDefault": "#cccccc",
  "ColorTextButtonInfoHover": "#cccccc",
  "ColorTextButtonInfoActive": "#cccccc",
  "ColorTextButtonInfoDisabled": "#cccccc",
  "ColorTextButtonWarningDefault": "#cccccc",
  "ColorTextButtonWarningHover": "#cccccc",
  "ColorTextButtonWarningActive": "#cccccc",
  "ColorTextButtonWarningDisabled": "#cccccc",
  "ColorTextButtonDestructiveDefault": "#cccccc",
  "ColorTextButtonDestructiveHover": "#cccccc",
  "ColorTextButtonDestructiveActive": "#cccccc",
  "ColorTextButtonDestructiveDisabled": "#cccccc",
  "ColorTextButtonSuccessDefault": "#cccccc",
  "ColorTextButtonSuccessHover": "#cccccc",
  "ColorTextButtonSuccessActive": "#cccccc",
  "ColorTextButtonSuccessDisabled": "#cccccc",
  "ColorTextButtonTertiaryDefault": "#cccccc",
  "ColorTextButtonTertiaryHover": "#cccccc",
  "ColorTextButtonTertiaryActive": "#cccccc",
  "ColorTextButtonTertiaryDisabled": "#cccccc",
  "ColorTextButtonSecondaryDefault": "#cccccc",
  "ColorTextButtonSecondaryHover": "#cccccc",
  "ColorTextButtonSecondaryActive": "#cccccc",
  "ColorTextButtonSecondaryDisabled": "#cccccc",
  "ColorTextButtonPrimaryDefault": "#cccccc",
  "ColorTextButtonPrimaryHover": "#cccccc",
  "ColorTextButtonPrimaryActive": "#cccccc",
  "ColorTextButtonPrimaryDisabled": "#cccccc",
  "ColorTextHeader400": "#cccccc",
  "ColorTextHeader600": "#f5f5f5",
  "ColorTextHeader800": "#ebebeb",
  "ColorTextBody400": "#cccccc",
  "ColorTextBody600": "#f5f5f5",
  "ColorTextBody800": "#ebebeb",
  "ColorSeparator200": "#cccccc",
  "ColorSeparator400": "#cccccc",
  "ColorSeparator600": "#f5f5f5",
  "ColorSeparator800": "#ebebeb",
  "ColorButtonBackgroundPrimaryDefault": "#cccccc",
  "ColorButtonBackgroundPrimaryHover": "#cccccc",
  "ColorButtonBackgroundPrimaryActive": "#cccccc",
  "ColorButtonBackgroundPrimaryDisabled": "#cccccc",
  "ColorButtonBackgroundSecondaryDefault": "#cccccc",
  "ColorButtonBackgroundSecondaryHover": "#cccccc",
  "ColorButtonBackgroundSecondaryActive": "#cccccc",
  "ColorButtonBackgroundSecondaryDisabled": "#cccccc",
  "ColorButtonBackgroundTertiaryDefault": "#cccccc",
  "ColorButtonBackgroundTertiaryHover": "#cccccc",
  "ColorButtonBackgroundTertiaryActive": "#cccccc",
  "ColorButtonBackgroundTertiaryDisabled": "#cccccc",
  "ColorButtonBackgroundSuccessDefault": "#cccccc",
  "ColorButtonBackgroundSuccessHover": "#cccccc",
  "ColorButtonBackgroundSuccessActive": "#cccccc",
  "ColorButtonBackgroundSuccessDisabled": "#cccccc",
  "ColorButtonBackgroundDestructiveDefault": "#cccccc",
  "ColorButtonBackgroundDestructiveHover": "#cccccc",
  "ColorButtonBackgroundDestructiveActive": "#cccccc",
  "ColorButtonBackgroundDestructiveDisabled": "#cccccc",
  "ColorButtonBackgroundWarningDefault": "#cccccc",
  "ColorButtonBackgroundWarningHover": "#cccccc",
  "ColorButtonBackgroundWarningActive": "#cccccc",
  "ColorButtonBackgroundWarningDisabled": "#cccccc",
  "ColorButtonBackgroundInfoDefault": "#cccccc",
  "ColorButtonBackgroundInfoHover": "#cccccc",
  "ColorButtonBackgroundInfoActive": "#cccccc",
  "ColorButtonBackgroundInfoDisabled": "#cccccc",
  "ColorButtonBackgroundSystemDefault": "#cccccc",
  "ColorButtonBackgroundSystemHover": "#cccccc",
  "ColorButtonBackgroundSystemActive": "#cccccc",
  "ColorButtonBackgroundSystemDisabled": "#cccccc",
  "ColorButtonBackgroundNeutralDefault": "#cccccc",
  "ColorButtonBackgroundNeutralHover": "#cccccc",
  "ColorButtonBackgroundNeutralActive": "#cccccc",
  "ColorButtonBackgroundNeutralDisabled": "#cccccc",
  "ColorButtonTextButtonNeutralDefault": "#cccccc",
  "ColorButtonTextButtonNeutralHover": "#cccccc",
  "ColorButtonTextButtonNeutralActive": "#cccccc",
  "ColorButtonTextButtonNeutralDisabled": "#cccccc",
  "ColorButtonTextButtonSystemDefault": "#cccccc",
  "ColorButtonTextButtonSystemHover": "#cccccc",
  "ColorButtonTextButtonSystemActive": "#cccccc",
  "ColorButtonTextButtonSystemDisabled": "#cccccc",
  "ColorButtonTextButtonInfoDefault": "#cccccc",
  "ColorButtonTextButtonInfoHover": "#cccccc",
  "ColorButtonTextButtonInfoActive": "#cccccc",
  "ColorButtonTextButtonInfoDisabled": "#cccccc",
  "ColorButtonTextButtonWarningDefault": "#cccccc",
  "ColorButtonTextButtonWarningHover": "#cccccc",
  "ColorButtonTextButtonWarningActive": "#cccccc",
  "ColorButtonTextButtonWarningDisabled": "#cccccc",
  "ColorButtonTextButtonDestructiveDefault": "#cccccc",
  "ColorButtonTextButtonDestructiveHover": "#cccccc",
  "ColorButtonTextButtonDestructiveActive": "#cccccc",
  "ColorButtonTextButtonDestructiveDisabled": "#cccccc",
  "ColorButtonTextButtonSuccessDefault": "#cccccc",
  "ColorButtonTextButtonSuccessHover": "#cccccc",
  "ColorButtonTextButtonSuccessActive": "#cccccc",
  "ColorButtonTextButtonSuccessDisabled": "#cccccc",
  "ColorButtonTextButtonTertiaryDefault": "#cccccc",
  "ColorButtonTextButtonTertiaryHover": "#cccccc",
  "ColorButtonTextButtonTertiaryActive": "#cccccc",
  "ColorButtonTextButtonTertiaryDisabled": "#cccccc",
  "ColorButtonTextButtonSecondaryDefault": "#cccccc",
  "ColorButtonTextButtonSecondaryHover": "#cccccc",
  "ColorButtonTextButtonSecondaryActive": "#cccccc",
  "ColorButtonTextButtonSecondaryDisabled": "#cccccc",
  "ColorButtonTextButtonPrimaryDefault": "#cccccc",
  "ColorButtonTextButtonPrimaryHover": "#cccccc",
  "ColorButtonTextButtonPrimaryActive": "#cccccc",
  "ColorButtonTextButtonPrimaryDisabled": "#cccccc",
  "ColorButtonTextHeader400": "#cccccc",
  "ColorButtonTextHeader600": "#f5f5f5",
  "ColorButtonTextHeader800": "#ebebeb",
  "ColorButtonTextBody400": "#cccccc",
  "ColorButtonTextBody600": "#f5f5f5",
  "ColorButtonTextBody800": "#ebebeb",
  "ColorButtonSeparator200": "#cccccc",
  "ColorButtonSeparator400": "#cccccc",
  "ColorButtonSeparator600": "#f5f5f5",
  "ColorButtonSeparator800": "#ebebeb",
  "ColorButtonIconButtonPrimaryDefault": "#cccccc",
  "ColorButtonIconButtonPrimaryHover": "#cccccc",
  "ColorButtonIconButtonPrimaryActive": "#cccccc",
  "ColorButtonIconButtonPrimaryDisabled": "#cccccc",
  "ColorButtonIconButtonSecondaryDefault": "#cccccc",
  "ColorButtonIconButtonSecondaryHover": "#cccccc",
  "ColorButtonIconButtonSecondaryActive": "#cccccc",
  "ColorButtonIconButtonSecondaryDisabled": "#cccccc",
  "ColorButtonIconButtonTertiaryDefault": "#cccccc",
  "ColorButtonIconButtonTertiaryHover": "#cccccc",
  "ColorButtonIconButtonTertiaryActive": "#cccccc",
  "ColorButtonIconButtonTertiaryDisabled": "#cccccc",
  "ColorButtonIconButtonSuccessDefault": "#cccccc",
  "ColorButtonIconButtonSuccessHover": "#cccccc",
  "ColorButtonIconButtonSuccessActive": "#cccccc",
  "ColorButtonIconButtonSuccessDisabled": "#cccccc",
  "ColorButtonIconButtonDestructiveDefault": "#cccccc",
  "ColorButtonIconButtonDestructiveHover": "#cccccc",
  "ColorButtonIconButtonDestructiveActive": "#cccccc",
  "ColorButtonIconButtonDestructiveDisabled": "#cccccc",
  "ColorButtonIconButtonWarningDefault": "#cccccc",
  "ColorButtonIconButtonWarningHover": "#cccccc",
  "ColorButtonIconButtonWarningActive": "#cccccc",
  "ColorButtonIconButtonWarningDisabled": "#cccccc",
  "ColorButtonIconButtonInfoDefault": "#cccccc",
  "ColorButtonIconButtonInfoHover": "#cccccc",
  "ColorButtonIconButtonInfoActive": "#cccccc",
  "ColorButtonIconButtonInfoDisabled": "#cccccc",
  "ColorButtonIconButtonSystemDefault": "#cccccc",
  "ColorButtonIconButtonSystemHover": "#cccccc",
  "ColorButtonIconButtonSystemActive": "#cccccc",
  "ColorButtonIconButtonSystemDisabled": "#cccccc",
  "ColorButtonIconButtonNeutralDefault": "#cccccc",
  "ColorButtonIconButtonNeutralHover": "#cccccc",
  "ColorButtonIconButtonNeutralActive": "#cccccc",
  "ColorButtonIconButtonNeutralDisabled": "#cccccc",
  "ColorSilver": "#cccccc",
  "ColorNickel": "#555555",
  "ColorCoal": "#333333",
  "ColorJet": "#222222",
  "ColorMidnight": "#111111",
  "ColorSmoke": "#ebebeb",
  "ColorBlackOpac70": "rgba(0, 0, 0, 0.7)",
  "ColorLightBlue": "#66c7ff",
  "ColorBlue": "#0274b6",
  "ColorDarkBlue": "#015483",
  "ColorLightPurple": "#c0a1ff",
  "ColorPurple": "#8856cb",
  "ColorDarkPurple": "#59348a",
  "ColorLightRed": "#ff8585",
  "ColorRed": "#e10000",
  "ColorDarkRed": "#ba0000",
  "ColorLightGreen": "#73ef69",
  "ColorGreen": "#0a8200",
  "ColorDarkGreen": "#064f00",
  "ColorLightYellow": "#ffecb1",
  "ColorYellow": "#ffcf3d",
  "ColorDarkYellow": "#5b3d2f",
  "ColorLightGold": "#9e855e",
  "ColorGold": "#816d4d",
  "ColorDarkGold": "#69583e",
  "ColorPalettePrimaryPrimary015": "#f0f9fe",
  "ColorPalettePrimaryPrimary025": "#e2f3fe",
  "ColorPalettePrimaryPrimary050": "#c0e8ff",
  "ColorPalettePrimaryPrimary075": "#66c7ff",
  "ColorPalettePrimaryPrimary085": "#54b4ee",
  "ColorPalettePrimaryPrimary100": "#3798d6",
  "ColorPalettePrimaryPrimary200": "#278aca",
  "ColorPalettePrimaryPrimary300": "#147cbd",
  "ColorPalettePrimaryPrimary400": "#0274b6",
  "ColorPalettePrimaryPrimary500": "#00639b",
  "ColorPalettePrimaryPrimary600": "#015483",
  "ColorPalettePrimaryPrimary700": "#003353",
  "ColorPalettePrimaryPrimary800": "#012841",
  "ColorPalettePrimaryPrimary900": "#001d32",
  "ColorPaletteSecondarySecondary015": "#f9f7ff",
  "ColorPaletteSecondarySecondary025": "#f3eefe",
  "ColorPaletteSecondarySecondary050": "#e7defe",
  "ColorPaletteSecondarySecondary075": "#d2bbff",
  "ColorPaletteSecondarySecondary085": "#c0a1ff",
  "ColorPaletteSecondarySecondary100": "#a47de6",
  "ColorPaletteSecondarySecondary200": "#996ddb",
  "ColorPaletteSecondarySecondary300": "#8d5ed0",
  "ColorPaletteSecondarySecondary400": "#8856cb",
  "ColorPaletteSecondarySecondary500": "#7347ae",
  "ColorPaletteSecondarySecondary600": "#59348a",
  "ColorPaletteSecondarySecondary700": "#3d2162",
  "ColorPaletteSecondarySecondary800": "#301a4d",
  "ColorPaletteSecondarySecondary900": "#24123b",
  "ColorPaletteTertiaryTertiary015": "#faf8f5",
  "ColorPaletteTertiaryTertiary025": "#f4f0eb",
  "ColorPaletteTertiaryTertiary050": "#e8e2d9",
  "ColorPaletteTertiaryTertiary075": "#d2c5b3",
  "ColorPaletteTertiaryTertiary085": "#bba98e",
  "ColorPaletteTertiaryTertiary100": "#a58d69",
  "ColorPaletteTertiaryTertiary200": "#9e855e",
  "ColorPaletteTertiaryTertiary300": "#887351",
  "ColorPaletteTertiaryTertiary400": "#816d4d",
  "ColorPaletteTertiaryTertiary500": "#69583e",
  "ColorPaletteTertiaryTertiary600": "#534530",
  "ColorPaletteTertiaryTertiary700": "#392f1f",
  "ColorPaletteTertiaryTertiary800": "#2d2418",
  "ColorPaletteTertiaryTertiary900": "#211b10",
  "ColorPalettePositivePositive015": "#ecfdea",
  "ColorPalettePositivePositive025": "#d3fcce",
  "ColorPalettePositivePositive050": "#aaf5a3",
  "ColorPalettePositivePositive075": "#73ef69",
  "ColorPalettePositivePositive085": "#4dc244",
  "ColorPalettePositivePositive100": "#35a62d",
  "ColorPalettePositivePositive200": "#28981f",
  "ColorPalettePositivePositive300": "#19890f",
  "ColorPalettePositivePositive400": "#0a8200",
  "ColorPalettePositivePositive500": "#096e00",
  "ColorPalettePositivePositive600": "#064f00",
  "ColorPalettePositivePositive700": "#043902",
  "ColorPalettePositivePositive800": "#022d00",
  "ColorPalettePositivePositive900": "#002200",
  "ColorPaletteNegativeNegative015": "#fff6f5",
  "ColorPaletteNegativeNegative025": "#ffeceb",
  "ColorPaletteNegativeNegative050": "#fedad8",
  "ColorPaletteNegativeNegative075": "#ffb3b1",
  "ColorPaletteNegativeNegative085": "#ff8585",
  "ColorPaletteNegativeNegative100": "#f35f5a",
  "ColorPaletteNegativeNegative200": "#ed4740",
  "ColorPaletteNegativeNegative300": "#e5261f",
  "ColorPaletteNegativeNegative400": "#e10000",
  "ColorPaletteNegativeNegative500": "#ba0000",
  "ColorPaletteNegativeNegative600": "#930201",
  "ColorPaletteNegativeNegative700": "#690000",
  "ColorPaletteNegativeNegative800": "#540202",
  "ColorPaletteNegativeNegative900": "#410000",
  "ColorPaletteHighlightHighlight015": "#fff8e3",
  "ColorPaletteHighlightHighlight025": "#ffecb1",
  "ColorPaletteHighlightHighlight050": "#fee08c",
  "ColorPaletteHighlightHighlight075": "#ffcf3d",
  "ColorPaletteHighlightHighlight085": "#d0a53d",
  "ColorPaletteHighlightHighlight100": "#b28b3e",
  "ColorPaletteHighlightHighlight200": "#a37d3d",
  "ColorPaletteHighlightHighlight300": "#94703a",
  "ColorPaletteHighlightHighlight400": "#876438",
  "ColorPaletteHighlightHighlight500": "#795836",
  "ColorPaletteHighlightHighlight600": "#5b3d2f",
  "ColorPaletteHighlightHighlight700": "#412b20",
  "ColorPaletteHighlightHighlight800": "#342118",
  "ColorPaletteHighlightHighlight900": "#271810",
  "ColorPaletteInfoInfo015": "#f3f8ff",
  "ColorPaletteInfoInfo025": "#e8f2ff",
  "ColorPaletteInfoInfo050": "#d3e4fe",
  "ColorPaletteInfoInfo075": "#a6c8ff",
  "ColorPaletteInfoInfo085": "#7babff",
  "ColorPaletteInfoInfo100": "#518dff",
  "ColorPaletteInfoInfo200": "#3a7efd",
  "ColorPaletteInfoInfo300": "#206cff",
  "ColorPaletteInfoInfo400": "#0f62fe",
  "ColorPaletteInfoInfo500": "#0353da",
  "ColorPaletteInfoInfo600": "#093ea6",
  "ColorPaletteInfoInfo700": "#012979",
  "ColorPaletteInfoInfo800": "#05205f",
  "ColorPaletteInfoInfo900": "#01174b",
  "ColorPaletteSystemSystem015": "#f3f9ff",
  "ColorPaletteSystemSystem025": "#e5f2ff",
  "ColorPaletteSystemSystem050": "#cfe4ff",
  "ColorPaletteSystemSystem075": "#a0c9ff",
  "ColorPaletteSystemSystem085": "#70adff",
  "ColorPaletteSystemSystem100": "#3e90fd",
  "ColorPaletteSystemSystem200": "#007aff",
  "ColorPaletteSystemSystem300": "#0472ee",
  "ColorPaletteSystemSystem400": "#0a66d8",
  "ColorPaletteSystemSystem500": "#005bc0",
  "ColorPaletteSystemSystem600": "#034493",
  "ColorPaletteSystemSystem700": "#032e68",
  "ColorPaletteSystemSystem800": "#002456",
  "ColorPaletteSystemSystem900": "#011a41",
  "ColorPaletteNeutralNeutral015": "#f5f5f5",
  "ColorPaletteNeutralNeutral025": "#ebebeb",
  "ColorPaletteNeutralNeutral050": "#e2e2e2",
  "ColorPaletteNeutralNeutral075": "#cccccc",
  "ColorPaletteNeutralNeutral085": "#ababab",
  "ColorPaletteNeutralNeutral100": "#919191",
  "ColorPaletteNeutralNeutral200": "#848484",
  "ColorPaletteNeutralNeutral300": "#767676",
  "ColorPaletteNeutralNeutral400": "#6f6f6f",
  "ColorPaletteNeutralNeutral500": "#555555",
  "ColorPaletteNeutralNeutral600": "#333333",
  "ColorPaletteNeutralNeutral700": "#222222",
  "ColorPaletteNeutralNeutral800": "#1b1b1b",
  "ColorPaletteNeutralNeutral900": "#111111",
  "ColorPaletteNeutralBWBlack": "#000000",
  "ColorPaletteNeutralBWWhite": "#ffffff",
  "ColorPaletteAlphaBlackBlack005": "rgba(0, 0, 0, 0.05)",
  "ColorPaletteAlphaBlackBlack010": "rgba(0, 0, 0, 0.1)",
  "ColorPaletteAlphaBlackBlack020": "rgba(0, 0, 0, 0.2)",
  "ColorPaletteAlphaBlackBlack030": "rgba(0, 0, 0, 0.3)",
  "ColorPaletteAlphaBlackBlack040": "rgba(0, 0, 0, 0.4)",
  "ColorPaletteAlphaBlackBlack050": "rgba(0, 0, 0, 0.5)",
  "ColorPaletteAlphaBlackBlack060": "rgba(0, 0, 0, 0.6)",
  "ColorPaletteAlphaBlackBlack070": "rgba(0, 0, 0, 0.7)",
  "ColorPaletteAlphaBlackBlack080": "rgba(0, 0, 0, 0.8)",
  "ColorPaletteAlphaBlackBlack090": "rgba(0, 0, 0, 0.9)",
  "ColorPaletteAlphaBlackBlack095": "rgba(0, 0, 0, 0.95)",
  "ColorPaletteAlphaWhiteWhite005": "rgba(255, 255, 255, 0.05)",
  "ColorPaletteAlphaWhiteWhite010": "rgba(255, 255, 255, 0.1)",
  "ColorPaletteAlphaWhiteWhite020": "rgba(255, 255, 255, 0.2)",
  "ColorPaletteAlphaWhiteWhite030": "rgba(255, 255, 255, 0.3)",
  "ColorPaletteAlphaWhiteWhite040": "rgba(255, 255, 255, 0.4)",
  "ColorPaletteAlphaWhiteWhite050": "rgba(255, 255, 255, 0.5)",
  "ColorPaletteAlphaWhiteWhite060": "rgba(255, 255, 255, 0.6)",
  "ColorPaletteAlphaWhiteWhite070": "rgba(255, 255, 255, 0.7)",
  "ColorPaletteAlphaWhiteWhite080": "rgba(255, 255, 255, 0.8)",
  "ColorPaletteAlphaWhiteWhite090": "rgba(255, 255, 255, 0.9)",
  "ColorPaletteAlphaWhiteWhite095": "rgba(255, 255, 255, 0.95)",
  "ElevationCardX": "0",
  "ElevationCardY": "1",
  "ElevationCardBlur": "2",
  "ElevationCardSpread": "1",
  "ElevationCardColorLight": "rgba(0, 0, 0, 0.1)",
  "ElevationCardColorDark": "rgba(255, 255, 255, 0.5)",
  "ElevationDropdownX": "0",
  "ElevationDropdownY": "3",
  "ElevationDropdownBlur": "7",
  "ElevationDropdownSpread": "-4",
  "ElevationDropdownColorLight": "rgba(0, 0, 0, 0.1)",
  "ElevationDropdownColorDark": "rgba(255, 255, 255, 0.5)",
  "FontFamilyRetina": "Retina",
  "FontFamilyExchange": "Exchange",
  "FontFamilyEscrowCondensed": "Escrow Condensed",
  "FontFamilyRetinaNarrow": "Retina Narrow",
  "FontFamilyRetinaWide": "Retina Wide",
  "FontFamilyHelvetica": "Helvetica",
  "FontFamilyArial": "Arial",
  "FontFamilyEscrowBanner": "Escrow Banner",
  "FontFamilyGeorgia": "Georgia",
  "FontFamilySerif": "serif",
  "FontFamilySansSerif": "sans-serif",
  "FontWeightThin": 100,
  "FontWeightExtraLight": 200,
  "FontWeightLight": 300,
  "FontWeightRegular": 400,
  "FontWeightMedium": 500,
  "FontWeightSemiBold": 600,
  "FontWeightBold": 700,
  "FontWeightExtraBold": 800,
  "FontWeightUltraBold": 900,
  "FontStyleNormal": "normal",
  "FontStyleItalic": "italic",
  "FontCaseSentence": "sentence",
  "FontCaseUppercase": "uppercase",
  "FontLetterSpacing1": 1,
  "FontLetterSpacing05": 0.5,
  "FontLetterSpacing08": 0.8,
  "FontFontStackEscrowBanner": "Escrow Banner, Georgia, serif",
  "FontFontStackEscrowCondensed": "Escrow Condensed, Georgia, serif",
  "FontFontStackExchange": "Exchange, Georgia, serif",
  "FontFontStackRetina": "Retina, Helvetica, Arial, sans-serif",
  "FontFontStackRetinaNarrow": "Retina Narrow, Helvetica, Arial, sans-serif",
  "FontFontStackRetinaWide": "Retina Wide, Helvetica, Arial,sans-serif",
  "FontTextTransformSentence": "capitalize",
  "FontTextTransformUppercase": "uppercase",
  "SpacingSpacer48": 48,
  "SpacingSpacer36": 36,
  "SpacingSpacer32": 32,
  "SpacingSpacer24": 24,
  "SpacingSpacer20": 20,
  "SpacingSpacer16": 16,
  "SpacingSpacer12": 12,
  "SpacingSpacer8": 8,
  "SpacingSpacer4": 4,
  "TypographyBodyFontSizeM": 17,
  "TypographyBodyFontSizeS": 15,
  "TypographyBodyFontLineHeightM": 28,
  "TypographyBodyFontLineHeightS": 24,
  "TypographyBodyStandardMFontSize": 17,
  "TypographyBodyStandardMLineHeight": 28,
  "TypographyBodyStandardMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyBodyStandardMFontWeight": 400,
  "TypographyBodySerifMFontSize": 17,
  "TypographyBodySerifMLineHeight": 28,
  "TypographyBodySerifMFontFamily": "Exchange, Georgia, serif",
  "TypographyBodySerifMFontWeight": 400,
  "TypographyBodySerifSFontSize": 15,
  "TypographyBodySerifSLineHeight": 24,
  "TypographyBodySerifSFontFamily": "Exchange",
  "TypographyBodySerifSFontWeight": 400,
  "TypographyBylineFontSizeM": 17,
  "TypographyBylineFontSizeS": 14,
  "TypographyBylineFontLineHeightM": 28,
  "TypographyBylineFontLineHeightS": 20,
  "TypographyBylineStandardMFontSize": 17,
  "TypographyBylineStandardMLineHeight": 28,
  "TypographyBylineStandardMFontFamily": "Exchange, Georgia, serif",
  "TypographyBylineStandardMFontWeight": 400,
  "TypographyBylineStandardMFontStyle": "italic",
  "TypographyBylineStandardSFontSize": 14,
  "TypographyBylineStandardSLineHeight": 20,
  "TypographyBylineStandardSFontFamily": "Exchange",
  "TypographyBylineStandardSFontWeight": 400,
  "TypographyBylineStandardSFontStyle": "italic",
  "TypographyCaptionFontSizeM": 14,
  "TypographyCaptionFontSizeS": 13,
  "TypographyCaptionFontLineHeightM": 20,
  "TypographyCaptionStandardMFontSize": 14,
  "TypographyCaptionStandardMLineHeight": 20,
  "TypographyCaptionStandardMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyCaptionStandardMFontWeight": 300,
  "TypographyCaptionStandardSFontSize": 13,
  "TypographyCaptionStandardSLineHeight": 20,
  "TypographyCaptionStandardSFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyCaptionStandardSFontWeight": 300,
  "TypographyFlashlineFontSizeM": 13,
  "TypographyFlashlineFontLineHeightM": 16,
  "TypographyFlashlineStandardMFontSize": 13,
  "TypographyFlashlineStandardMLineHeight": 16,
  "TypographyFlashlineStandardMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyFlashlineStandardMFontWeight": 500,
  "TypographyFlashlineStandardMLetterSpacing": 0.8,
  "TypographyFlashlineStandardMCase": "uppercase",
  "TypographyFlashlineStandardMTextTransform": "uppercase",
  "TypographyFlashlineOpinionMFontSize": 13,
  "TypographyFlashlineOpinionMLineHeight": 16,
  "TypographyFlashlineOpinionMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyFlashlineOpinionMFontWeight": 500,
  "TypographyFlashlineOpinionMLetterSpacing": 0.8,
  "TypographyFlashlineOpinionMCase": "uppercase",
  "TypographyFlashlineOpinionMTextTransform": "uppercase",
  "TypographyFlashlinePriorityMFontSize": 13,
  "TypographyFlashlinePriorityMLineHeight": 16,
  "TypographyFlashlinePriorityMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyFlashlinePriorityMFontWeight": 500,
  "TypographyFlashlinePriorityMLetterSpacing": 0.8,
  "TypographyFlashlinePriorityMCase": "uppercase",
  "TypographyFlashlinePriorityMTextTransform": "uppercase",
  "TypographyFlashlineMagazineMFontSize": 13,
  "TypographyFlashlineMagazineMLineHeight": 16,
  "TypographyFlashlineMagazineMFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyFlashlineMagazineMFontWeight": 300,
  "TypographyFlashlineMagazineMLetterSpacing": 1,
  "TypographyFlashlineMagazineMCase": "uppercase",
  "TypographyFlashlineMagazineMTextTransform": "uppercase",
  "TypographyHeadlineFontSizeXxl": 40,
  "TypographyHeadlineFontSizeXl": 36,
  "TypographyHeadlineFontSizeL": 32,
  "TypographyHeadlineFontSizeM": 28,
  "TypographyHeadlineFontSizeS": 22,
  "TypographyHeadlineFontSizeXs": 18,
  "TypographyHeadlineFontSizeXxs": 16,
  "TypographyHeadlineFontLineHeightXxl": 40,
  "TypographyHeadlineFontLineHeightXl": 36,
  "TypographyHeadlineFontLineHeightL": 36,
  "TypographyHeadlineFontLineHeightM": 32,
  "TypographyHeadlineFontLineHeightS": 24,
  "TypographyHeadlineFontLineHeightXs": 20,
  "TypographyHeadlineFontLineHeightXxs": 24,
  "TypographyHeadlineStandardXxlFontSize": 40,
  "TypographyHeadlineStandardXxlLineHeight": 40,
  "TypographyHeadlineStandardXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardXxlFontWeight": 700,
  "TypographyHeadlineStandardXxlTextTransform": "capitalize",
  "TypographyHeadlineStandardXlFontSize": 36,
  "TypographyHeadlineStandardXlLineHeight": 36,
  "TypographyHeadlineStandardXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardXlFontWeight": 700,
  "TypographyHeadlineStandardXlTextTransform": "capitalize",
  "TypographyHeadlineStandardLFontSize": 32,
  "TypographyHeadlineStandardLLineHeight": 36,
  "TypographyHeadlineStandardLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardLFontWeight": 700,
  "TypographyHeadlineStandardLTextTransform": "capitalize",
  "TypographyHeadlineStandardMFontSize": 28,
  "TypographyHeadlineStandardMLineHeight": 32,
  "TypographyHeadlineStandardMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardMFontWeight": 700,
  "TypographyHeadlineStandardMTextTransform": "capitalize",
  "TypographyHeadlineStandardSFontSize": 22,
  "TypographyHeadlineStandardSLineHeight": 24,
  "TypographyHeadlineStandardSFontFamily": "Escrow Condensed",
  "TypographyHeadlineStandardSFontWeight": 700,
  "TypographyHeadlineStandardXsFontSize": 18,
  "TypographyHeadlineStandardXsLineHeight": 20,
  "TypographyHeadlineStandardXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineStandardXsFontWeight": 700,
  "TypographyHeadlineStandardXsTextTransform": "capitalize",
  "TypographyHeadlineStandardXxsFontSize": 16,
  "TypographyHeadlineStandardXxsLineHeight": 24,
  "TypographyHeadlineStandardXxsFontFamily": "Exchange, Georgia, serif",
  "TypographyHeadlineStandardXxsFontWeight": 500,
  "TypographyHeadlineStandardXxsTextTransform": "capitalize",
  "TypographyHeadlineOpinionXxlFontSize": 40,
  "TypographyHeadlineOpinionXxlLineHeight": 40,
  "TypographyHeadlineOpinionXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXxlFontStyle": "italic",
  "TypographyHeadlineOpinionXxlFontWeight": 400,
  "TypographyHeadlineOpinionXxlTextTransform": "capitalize",
  "TypographyHeadlineOpinionXlFontSize": 36,
  "TypographyHeadlineOpinionXlLineHeight": 36,
  "TypographyHeadlineOpinionXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXlFontStyle": "italic",
  "TypographyHeadlineOpinionXlFontWeight": 400,
  "TypographyHeadlineOpinionXlTextTransform": "capitalize",
  "TypographyHeadlineOpinionLFontSize": 32,
  "TypographyHeadlineOpinionLLineHeight": 36,
  "TypographyHeadlineOpinionLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionLFontStyle": "italic",
  "TypographyHeadlineOpinionLFontWeight": 400,
  "TypographyHeadlineOpinionLTextTransform": "capitalize",
  "TypographyHeadlineOpinionMFontSize": 28,
  "TypographyHeadlineOpinionMLineHeight": 32,
  "TypographyHeadlineOpinionMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionMFontStyle": "italic",
  "TypographyHeadlineOpinionMFontWeight": 400,
  "TypographyHeadlineOpinionMTextTransform": "capitalize",
  "TypographyHeadlineOpinionSFontSize": 22,
  "TypographyHeadlineOpinionSLineHeight": 24,
  "TypographyHeadlineOpinionSFontFamily": "Escrow Condensed",
  "TypographyHeadlineOpinionSFontStyle": "italic",
  "TypographyHeadlineOpinionSFontWeight": 400,
  "TypographyHeadlineOpinionXsFontSize": 18,
  "TypographyHeadlineOpinionXsLineHeight": 20,
  "TypographyHeadlineOpinionXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXsFontStyle": "italic",
  "TypographyHeadlineOpinionXsFontWeight": 400,
  "TypographyHeadlineOpinionXsTextTransform": "capitalize",
  "TypographyHeadlineOpinionXxsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineOpinionXxsTextTransform": "capitalize",
  "TypographyHeadlineFeaturesXxlFontSize": 40,
  "TypographyHeadlineFeaturesXxlLineHeight": 40,
  "TypographyHeadlineFeaturesXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXxlFontWeight": 400,
  "TypographyHeadlineFeaturesXxlTextTransform": "capitalize",
  "TypographyHeadlineFeaturesXlFontSize": 36,
  "TypographyHeadlineFeaturesXlLineHeight": 36,
  "TypographyHeadlineFeaturesXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXlFontWeight": 400,
  "TypographyHeadlineFeaturesXlTextTransform": "capitalize",
  "TypographyHeadlineFeaturesLFontSize": 32,
  "TypographyHeadlineFeaturesLLineHeight": 36,
  "TypographyHeadlineFeaturesLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesLFontWeight": 400,
  "TypographyHeadlineFeaturesLTextTransform": "capitalize",
  "TypographyHeadlineFeaturesMFontSize": 28,
  "TypographyHeadlineFeaturesMLineHeight": 32,
  "TypographyHeadlineFeaturesMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesMFontWeight": 400,
  "TypographyHeadlineFeaturesMTextTransform": "capitalize",
  "TypographyHeadlineFeaturesSFontSize": 22,
  "TypographyHeadlineFeaturesSLineHeight": 24,
  "TypographyHeadlineFeaturesSFontFamily": "Escrow Condensed",
  "TypographyHeadlineFeaturesSFontWeight": 400,
  "TypographyHeadlineFeaturesXsFontSize": 18,
  "TypographyHeadlineFeaturesXsLineHeight": 20,
  "TypographyHeadlineFeaturesXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXsFontWeight": 400,
  "TypographyHeadlineFeaturesXsTextTransform": "capitalize",
  "TypographyHeadlineFeaturesXxsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineFeaturesXxsTextTransform": "capitalize",
  "TypographyHeadlineMagazineXxlFontSize": 40,
  "TypographyHeadlineMagazineXxlLineHeight": 40,
  "TypographyHeadlineMagazineXxlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXxlFontWeight": 300,
  "TypographyHeadlineMagazineXxlTextTransform": "capitalize",
  "TypographyHeadlineMagazineXlFontSize": 36,
  "TypographyHeadlineMagazineXlLineHeight": 36,
  "TypographyHeadlineMagazineXlFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXlFontWeight": 300,
  "TypographyHeadlineMagazineXlTextTransform": "capitalize",
  "TypographyHeadlineMagazineLFontSize": 32,
  "TypographyHeadlineMagazineLLineHeight": 36,
  "TypographyHeadlineMagazineLFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineLFontWeight": 300,
  "TypographyHeadlineMagazineLTextTransform": "capitalize",
  "TypographyHeadlineMagazineMFontSize": 28,
  "TypographyHeadlineMagazineMLineHeight": 32,
  "TypographyHeadlineMagazineMFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineMFontWeight": 300,
  "TypographyHeadlineMagazineMTextTransform": "capitalize",
  "TypographyHeadlineMagazineSFontSize": 22,
  "TypographyHeadlineMagazineSLineHeight": 24,
  "TypographyHeadlineMagazineSFontFamily": "Escrow Condensed",
  "TypographyHeadlineMagazineSFontWeight": 300,
  "TypographyHeadlineMagazineXsFontSize": 18,
  "TypographyHeadlineMagazineXsLineHeight": 20,
  "TypographyHeadlineMagazineXsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXsFontWeight": 300,
  "TypographyHeadlineMagazineXsTextTransform": "capitalize",
  "TypographyHeadlineMagazineXxsFontFamily": "Escrow Condensed, Georgia, serif",
  "TypographyHeadlineMagazineXxsTextTransform": "capitalize",
  "TypographyHeadlineOffplatformXxlFontSize": 32,
  "TypographyHeadlineOffplatformXxlLineHeight": 36,
  "TypographyHeadlineOffplatformXxlFontFamily": "Retina",
  "TypographyHeadlineOffplatformXxlFontWeight": 500,
  "TypographyStrapFontSizeM": 18,
  "TypographyStrapFontSizeS": 16,
  "TypographyStrapFontLineHeightM": 24,
  "TypographyStrapFontLineHeightS": 24,
  "TypographyStrapStandardMFontSize": 18,
  "TypographyStrapStandardMLineHeight": 24,
  "TypographyStrapStandardMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyStrapStandardMFontWeight": 500,
  "TypographyStrapStandardMTextTransform": "uppercase",
  "TypographyStrapStandardSFontSize": 16,
  "TypographyStrapStandardSLineHeight": 24,
  "TypographyStrapStandardSFontFamily": "Retina",
  "TypographyStrapStandardSFontWeight": 500,
  "TypographyStrapOpinionMFontSize": 18,
  "TypographyStrapOpinionMLineHeight": 24,
  "TypographyStrapOpinionMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyStrapOpinionMFontWeight": 500,
  "TypographyStrapOpinionMTextTransform": "uppercase",
  "TypographyStrapPriorityMFontSize": 18,
  "TypographyStrapPriorityMLineHeight": 24,
  "TypographyStrapPriorityMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyStrapPriorityMFontWeight": 500,
  "TypographyStrapPriorityMTextTransform": "uppercase",
  "TypographyStrapMagazineMFontSize": 16,
  "TypographyStrapMagazineMLineHeight": 24,
  "TypographyStrapMagazineMFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyStrapMagazineMFontWeight": 300,
  "TypographyStrapMagazineMTextTransform": "uppercase",
  "TypographyStrapLinkFontSizeS": 16,
  "TypographyStrapLinkFontLineHeightS": 24,
  "TypographyStrapLinkStandardSFontSize": 16,
  "TypographyStrapLinkStandardSLineHeight": 24,
  "TypographyStrapLinkStandardSFontFamily": "Retina",
  "TypographyStrapLinkStandardSFontWeight": 300,
  "TypographySubheadingFontSizeM": 20,
  "TypographySubheadingFontSizeS": 17,
  "TypographySubheadingFontLineHeightM": 28,
  "TypographySubheadingFontLineHeightS": 24,
  "TypographySubheadingStandardMFontSize": 20,
  "TypographySubheadingStandardMLineHeight": 28,
  "TypographySubheadingStandardMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographySubheadingStandardMFontWeight": 300,
  "TypographySubheadingStandardMTextTransform": "capitalize",
  "TypographySubheadingStandardSFontSize": 17,
  "TypographySubheadingStandardSLineHeight": 24,
  "TypographySubheadingStandardSFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographySubheadingStandardSFontWeight": 300,
  "TypographySubheadingStandardSTextTransform": "capitalize",
  "TypographySubheadingSerifMFontSize": 20,
  "TypographySubheadingSerifMLineHeight": 28,
  "TypographySubheadingSerifMFontFamily": "Exchange, Georgia, serif",
  "TypographySubheadingSerifMFontWeight": 400,
  "TypographySubheadingSerifSFontSize": 17,
  "TypographySubheadingSerifSLineHeight": 24,
  "TypographySubheadingSerifSFontFamily": "Exchange, Georgia, serif",
  "TypographySubheadingSerifSFontWeight": 400,
  "TypographySummaryFontSizeM": 16,
  "TypographySummaryFontSizeS": 14,
  "TypographySummaryFontLineHeightM": 24,
  "TypographySummaryFontLineHeightS": 20,
  "TypographySummaryStandardMFontSize": 16,
  "TypographySummaryStandardMLineHeight": 24,
  "TypographySummaryStandardMFontFamily": "Exchange, Georgia, serif",
  "TypographySummaryStandardMFontWeight": 400,
  "TypographySummaryStandardSFontSize": 14,
  "TypographySummaryStandardSLineHeight": 20,
  "TypographySummaryStandardSFontFamily": "Exchange, Georgia, serif",
  "TypographySummaryStandardSFontWeight": 400,
  "TypographyTimestampFontSizeM": 14,
  "TypographyTimestampFontSizeS": 13,
  "TypographyTimestampFontSizeXs": 13,
  "TypographyTimestampFontLineHeightM": 16,
  "TypographyTimestampFontLineHeightXs": 16,
  "TypographyTimestampStandardXsFontSize": 13,
  "TypographyTimestampStandardXsLineHeight": 16,
  "TypographyTimestampStandardXsFontFamily": "Retina",
  "TypographyTimestampStandardXsFontWeight": 300,
  "TypographyTimestampStandardMFontSize": 14,
  "TypographyTimestampStandardMLineHeight": 16,
  "TypographyTimestampStandardMFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyTimestampStandardMFontWeight": 400,
  "TypographyTimestampStandardMTextTransform": "uppercase",
  "TypographyTimestampStandardSFontSize": 13,
  "TypographyTimestampStandardSLineHeight": 16,
  "TypographyTimestampStandardSFontFamily": "Retina Narrow, Helvetica, Arial, sans-serif",
  "TypographyTimestampStandardSFontWeight": 400,
  "TypographyTimestampStandardSTextTransform": "uppercase",
  "TypographySansSerifFontSizeStandardL": 18,
  "TypographySansSerifFontSizeStandardM": 16,
  "TypographySansSerifFontSizeStandardS": 14,
  "TypographySansSerifFontSizeStandardXs": 13,
  "TypographySansSerifFontSizeStandardXxs": 12,
  "TypographySansSerifFontSizeStandardXxxs": 10,
  "TypographySansSerifFontSizeCondensedXxl": 24,
  "TypographySansSerifFontSizeCondensedXl": 20,
  "TypographySansSerifFontSizeCondensedL": 18,
  "TypographySansSerifFontSizeCondensedM": 16,
  "TypographySansSerifFontSizeCapsTitleStandardL": 28,
  "TypographySansSerifFontSizeCapsTitleStandardM": 18,
  "TypographySansSerifFontSizeCapsTitleStandardS": 13,
  "TypographySansSerifFontSizeCapsTitleMagazineM": 16,
  "TypographySansSerifFontSizeCapsTitleMagazineS": 12,
  "TypographySansSerifFontLineHeightStandardL": 24,
  "TypographySansSerifFontLineHeightStandardM": 24,
  "TypographySansSerifFontLineHeightStandardS": 20,
  "TypographySansSerifFontLineHeightStandardXs": 16,
  "TypographySansSerifFontLineHeightStandardXxs": 16,
  "TypographySansSerifFontLineHeightStandardXxxs": 14,
  "TypographySansSerifFontLineHeightCondensedXxl": 28,
  "TypographySansSerifFontLineHeightCondensedXl": 24,
  "TypographySansSerifFontLineHeightCondensedL": 24,
  "TypographySansSerifFontLineHeightCondensedM": 20,
  "TypographySansSerifFontLineHeightCapsTitleStandardL": 32,
  "TypographySansSerifFontLineHeightCapsTitleStandardM": 24,
  "TypographySansSerifFontLineHeightCapsTitleStandardS": 16,
  "TypographySansSerifFontLineHeightCapsTitleMagazineM": 14,
  "TypographySansSerifFontLineHeightCapsTitleMagazineS": 16,
  "TypographySansSerifStandardLThickFontSize": 18,
  "TypographySansSerifStandardLThickLineHeight": 24,
  "TypographySansSerifStandardLThickFontFamily": "Retina",
  "TypographySansSerifStandardLThickFontWeight": 500,
  "TypographySansSerifStandardLThinFontSize": 18,
  "TypographySansSerifStandardLThinLineHeight": 24,
  "TypographySansSerifStandardLThinFontFamily": "Retina",
  "TypographySansSerifStandardLThinFontWeight": 300,
  "TypographySansSerifStandardMThickFontSize": 16,
  "TypographySansSerifStandardMThickLineHeight": 24,
  "TypographySansSerifStandardMThickFontFamily": "Retina",
  "TypographySansSerifStandardMThickFontWeight": 500,
  "TypographySansSerifStandardMThinFontSize": 16,
  "TypographySansSerifStandardMThinLineHeight": 24,
  "TypographySansSerifStandardMThinFontFamily": "Retina",
  "TypographySansSerifStandardMThinFontWeight": 300,
  "TypographySansSerifStandardSThickFontSize": 14,
  "TypographySansSerifStandardSThickLineHeight": 20,
  "TypographySansSerifStandardSThickFontFamily": "Retina",
  "TypographySansSerifStandardSThickFontWeight": 500,
  "TypographySansSerifStandardSThinFontSize": 14,
  "TypographySansSerifStandardSThinLineHeight": 20,
  "TypographySansSerifStandardSThinFontFamily": "Retina",
  "TypographySansSerifStandardSThinFontWeight": 300,
  "TypographySansSerifStandardXsThickFontSize": 13,
  "TypographySansSerifStandardXsThickLineHeight": 16,
  "TypographySansSerifStandardXsThickFontFamily": "Retina",
  "TypographySansSerifStandardXsThickFontWeight": 500,
  "TypographySansSerifStandardXsThinFontSize": 13,
  "TypographySansSerifStandardXsThinLineHeight": 16,
  "TypographySansSerifStandardXsThinFontFamily": "Retina",
  "TypographySansSerifStandardXsThinFontWeight": 300,
  "TypographySansSerifStandardXxsThickFontSize": 12,
  "TypographySansSerifStandardXxsThickLineHeight": 16,
  "TypographySansSerifStandardXxsThickFontFamily": "Retina",
  "TypographySansSerifStandardXxsThickFontWeight": 500,
  "TypographySansSerifStandardXxsThinFontSize": 12,
  "TypographySansSerifStandardXxsThinLineHeight": 16,
  "TypographySansSerifStandardXxsThinFontFamily": "Retina",
  "TypographySansSerifStandardXxsThinFontWeight": 300,
  "TypographySansSerifStandardXxxsThickFontSize": 10,
  "TypographySansSerifStandardXxxsThickLineHeight": 14,
  "TypographySansSerifStandardXxxsThickFontFamily": "Retina",
  "TypographySansSerifStandardXxxsThickFontWeight": 500,
  "TypographySansSerifStandardXxxsThinFontSize": 10,
  "TypographySansSerifStandardXxxsThinLineHeight": 14,
  "TypographySansSerifStandardXxxsThinFontFamily": "Retina",
  "TypographySansSerifStandardXxxsThinFontWeight": 300,
  "TypographySansSerifCondensedXxlThickFontSize": 24,
  "TypographySansSerifCondensedXxlThickLineHeight": 28,
  "TypographySansSerifCondensedXxlThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedXxlThickFontWeight": 500,
  "TypographySansSerifCondensedXlThickFontSize": 20,
  "TypographySansSerifCondensedXlThickLineHeight": 24,
  "TypographySansSerifCondensedXlThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedXlThickFontWeight": 500,
  "TypographySansSerifCondensedLThickFontSize": 18,
  "TypographySansSerifCondensedLThickLineHeight": 24,
  "TypographySansSerifCondensedLThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedLThickFontWeight": 500,
  "TypographySansSerifCondensedMThickFontSize": 16,
  "TypographySansSerifCondensedMThickLineHeight": 20,
  "TypographySansSerifCondensedMThickFontFamily": "Retina Narrow",
  "TypographySansSerifCondensedMThickFontWeight": 500,
  "TypographySansSerifCapsTitleLStandardFontSize": 28,
  "TypographySansSerifCapsTitleLStandardLineHeight": 32,
  "TypographySansSerifCapsTitleLStandardFontFamily": "Retina Narrow",
  "TypographySansSerifCapsTitleLStandardFontWeight": 700,
  "TypographySansSerifCapsTitleLStandardFontCase": "uppercase",
  "TypographySansSerifCapsTitleMStandardFontSize": 18,
  "TypographySansSerifCapsTitleMStandardLineHeight": 24,
  "TypographySansSerifCapsTitleMStandardFontFamily": "Retina Narrow",
  "TypographySansSerifCapsTitleMStandardFontWeight": 500,
  "TypographySansSerifCapsTitleMStandardFontCase": "uppercase",
  "TypographySansSerifCapsTitleMMagazineFontSize": 16,
  "TypographySansSerifCapsTitleMMagazineLineHeight": 14,
  "TypographySansSerifCapsTitleMMagazineFontFamily": "Retina Wide",
  "TypographySansSerifCapsTitleMMagazineFontWeight": 300,
  "TypographySansSerifCapsTitleMMagazineFontCase": "uppercase",
  "TypographySansSerifCapsTitleSStandardFontSize": 13,
  "TypographySansSerifCapsTitleSStandardLineHeight": 16,
  "TypographySansSerifCapsTitleSStandardFontFamily": "Retina Narrow",
  "TypographySansSerifCapsTitleSStandardFontWeight": 500,
  "TypographySansSerifCapsTitleSStandardFontCase": "uppercase",
  "TypographySansSerifCapsTitleSStandardFontLetterSpacing": 0.8,
  "TypographySansSerifCapsTitleSMagazineFontSize": 16,
  "TypographySansSerifCapsTitleSMagazineLineHeight": 14,
  "TypographySansSerifCapsTitleSMagazineFontFamily": "Retina Wide",
  "TypographySansSerifCapsTitleSMagazineFontWeight": 300,
  "TypographySansSerifCapsTitleSMagazineFontCase": "uppercase",
  "TypographySansSerifCapsTitleSMagazineFontLetterSpacing": 1,
  "BoxShadowCardDark": "0px 1px 2px 1px rgba(255, 255, 255, 0.5)",
  "BoxShadowCardLight": "0px 1px 2px 1px rgba(0, 0, 0, 0.1)",
  "BoxShadowDropdownDark": "0px 3px 7px -4px rgba(255, 255, 255, 0.5)",
  "BoxShadowDropdownLight": "0px 3px 7px -4px rgba(0, 0, 0, 0.1)"
}