module.exports = {
  "BorderRadiusM": 4,
  "BorderRadiusS": 2,
  "ColorWhite": "#ffffff",
  "ColorBlack": "#000000",
  "ColorSnow": "#f4f4f4",
  "ColorBlackOpac10": "rgba(0, 0, 0, 0.1)",
  "ColorWhiteOpac50": "rgba(255, 255, 255, 0.5)",
  "ColorTeal": "#007d7e",
  "ColorDarkTeal": "#00696b",
  "ColorLightTeal": "#009c9e",
  "ColorOffWhite": "#fffbf7",
  "ColorOffWhite10": "#e6e2de",
  "ColorOffWhite20": "#ccc9c6",
  "ColorTealOpac10": "rgba(0, 125, 126, 0.1)",
  "ColorNavy": "#151639",
  "ColorNavy75": "#50516b",
  "ColorNavy50": "#8a8a9c",
  "ColorNavy25": "#c4c5cd",
  "ColorDarkNavy": "#0b0c1f",
  "ElevationCardX": "0",
  "ElevationCardY": "1",
  "ElevationCardBlur": "2",
  "ElevationCardSpread": "1",
  "ElevationCardColorLight": "rgba(0, 0, 0, 0.1)",
  "ElevationCardColorDark": "rgba(255, 255, 255, 0.5)",
  "ElevationDropdownX": "0",
  "ElevationDropdownY": "3",
  "ElevationDropdownBlur": "7",
  "ElevationDropdownSpread": "-4",
  "ElevationDropdownColorLight": "rgba(0, 0, 0, 0.1)",
  "ElevationDropdownColorDark": "rgba(255, 255, 255, 0.5)",
  "FontFamilyRetina": "Retina",
  "FontFamilyExchange": "Exchange",
  "FontFamilyEscrowCondensed": "Escrow Condensed",
  "FontFamilyRetinaNarrow": "Retina Narrow",
  "FontFamilyRetinaWide": "Retina Wide",
  "FontFamilyHelvetica": "Helvetica",
  "FontFamilyArial": "Arial",
  "FontFamilyEscrowBanner": "Escrow Banner",
  "FontFamilyGeorgia": "Georgia",
  "FontFamilySerif": "serif",
  "FontFamilySansSerif": "sans-serif",
  "FontWeightThin": 100,
  "FontWeightExtraLight": 200,
  "FontWeightLight": 300,
  "FontWeightRegular": 400,
  "FontWeightMedium": 500,
  "FontWeightSemiBold": 600,
  "FontWeightBold": 700,
  "FontWeightExtraBold": 800,
  "FontWeightUltraBold": 900,
  "FontStyleNormal": "normal",
  "FontStyleItalic": "italic",
  "FontCaseSentence": "sentence",
  "FontCaseUppercase": "uppercase",
  "FontLetterSpacing1": 1,
  "FontLetterSpacing05": 0.5,
  "FontLetterSpacing08": 0.8,
  "FontFontStackEscrowBanner": "Escrow Banner, Georgia, serif",
  "FontFontStackEscrowCondensed": "Escrow Condensed, Georgia, serif",
  "FontFontStackExchange": "Exchange, Georgia, serif",
  "FontFontStackRetina": "Retina, Helvetica, Arial, sans-serif",
  "FontFontStackRetinaNarrow": "Retina Narrow, Helvetica, Arial, sans-serif",
  "FontFontStackRetinaWide": "Retina Wide, Helvetica, Arial,sans-serif",
  "FontTextTransformSentence": "capitalize",
  "FontTextTransformUppercase": "uppercase",
  "SpacingSpacer48": 48,
  "SpacingSpacer36": 36,
  "SpacingSpacer32": 32,
  "SpacingSpacer24": 24,
  "SpacingSpacer20": 20,
  "SpacingSpacer16": 16,
  "SpacingSpacer12": 12,
  "SpacingSpacer8": 8,
  "SpacingSpacer4": 4,
  "TypographyBodyFontSizeM": 17,
  "TypographyBodyFontLineHeightM": 27,
  "TypographyBodyStandardMFontSize": 17,
  "TypographyBodyStandardMLineHeight": 27,
  "TypographyBodyStandardMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyBodyStandardMFontWeight": 300,
  "TypographyBylineFontSizeM": 14,
  "TypographyBylineFontLineHeightM": 22,
  "TypographyBylineStandardMFontSize": 14,
  "TypographyBylineStandardMLineHeight": 22,
  "TypographyBylineStandardMFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyBylineStandardMFontWeight": 300,
  "TypographyBylineStandardMTextTransform": "uppercase",
  "TypographyCaptionFontSizeM": 16,
  "TypographyCaptionFontSizeS": 14,
  "TypographyCaptionFontLineHeightM": 24,
  "TypographyCaptionFontLineHeightS": 20,
  "TypographyCaptionPhotoMFontSize": 14,
  "TypographyCaptionPhotoMLineHeight": 20,
  "TypographyCaptionPhotoMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyCaptionPhotoMFontWeight": 300,
  "TypographyCaptionPhotoMTextTransform": "uppercase",
  "TypographyCaptionSurveyMFontSize": 16,
  "TypographyCaptionSurveyMLineHeight": 24,
  "TypographyCaptionSurveyMFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographyCaptionSurveyMFontWeight": 400,
  "TypographyFlashlineFontSizeL": 16,
  "TypographyFlashlineFontSizeS": 13,
  "TypographyFlashlineFontLineHeightL": 16,
  "TypographyFlashlineFontLineHeightS": 13,
  "TypographyFlashlineStandardLFontSize": 16,
  "TypographyFlashlineStandardLLineHeight": 16,
  "TypographyFlashlineStandardLFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyFlashlineStandardLFontWeight": 300,
  "TypographyFlashlineStandardLTextTransform": "uppercase",
  "TypographyFlashlineStandardSFontSize": 13,
  "TypographyFlashlineStandardSLineHeight": 13,
  "TypographyFlashlineStandardSFontFamily": "Retina Wide",
  "TypographyFlashlineStandardSFontWeight": 300,
  "TypographyFlashlineStandardMFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyFlashlineStandardMTextTransform": "uppercase",
  "TypographyHeadlineFontSizeXxl": 56,
  "TypographyHeadlineFontSizeXl": 50,
  "TypographyHeadlineFontSizeL": 40,
  "TypographyHeadlineFontSizeM": 32,
  "TypographyHeadlineFontSizeS": 28,
  "TypographyHeadlineFontSizeXs": 22,
  "TypographyHeadlineFontSizeXxs": 18,
  "TypographyHeadlineFontLineHeightXxl": 62,
  "TypographyHeadlineFontLineHeightXl": 54,
  "TypographyHeadlineFontLineHeightL": 44,
  "TypographyHeadlineFontLineHeightM": 34,
  "TypographyHeadlineFontLineHeightS": 30,
  "TypographyHeadlineFontLineHeightXs": 24,
  "TypographyHeadlineFontLineHeightXxs": 20,
  "TypographyHeadlineStandardXxlFontSize": 56,
  "TypographyHeadlineStandardXxlLineHeight": 62,
  "TypographyHeadlineStandardXxlFontFamily": "Escrow Banner, Georgia, serif",
  "TypographyHeadlineStandardXxlFontWeight": 900,
  "TypographyHeadlineStandardXxlTextTransform": "capitalize",
  "TypographyHeadlineStandardXlFontSize": 50,
  "TypographyHeadlineStandardXlLineHeight": 54,
  "TypographyHeadlineStandardXlFontFamily": "Escrow Banner, Georgia, serif",
  "TypographyHeadlineStandardXlFontWeight": 900,
  "TypographyHeadlineStandardXlTextTransform": "capitalize",
  "TypographyHeadlineStandardLFontSize": 40,
  "TypographyHeadlineStandardLLineHeight": 44,
  "TypographyHeadlineStandardLFontFamily": "Escrow Banner, Georgia, serif",
  "TypographyHeadlineStandardLFontWeight": 900,
  "TypographyHeadlineStandardLTextTransform": "capitalize",
  "TypographyHeadlineStandardMFontSize": 32,
  "TypographyHeadlineStandardMLineHeight": 34,
  "TypographyHeadlineStandardMFontFamily": "Escrow Banner, Georgia, serif",
  "TypographyHeadlineStandardMFontWeight": 900,
  "TypographyHeadlineStandardMTextTransform": "capitalize",
  "TypographyHeadlineStandardSFontSize": 28,
  "TypographyHeadlineStandardSLineHeight": 30,
  "TypographyHeadlineStandardSFontFamily": "Escrow Banner",
  "TypographyHeadlineStandardSFontWeight": 900,
  "TypographyHeadlineStandardXsFontSize": 22,
  "TypographyHeadlineStandardXsLineHeight": 24,
  "TypographyHeadlineStandardXsFontFamily": "Escrow Banner, Georgia, serif",
  "TypographyHeadlineStandardXsFontWeight": 900,
  "TypographyHeadlineStandardXsTextTransform": "capitalize",
  "TypographyHeadlineStandardXxsFontSize": 18,
  "TypographyHeadlineStandardXxsLineHeight": 20,
  "TypographyHeadlineStandardXxsFontFamily": "Escrow Banner, Georgia, serif",
  "TypographyHeadlineStandardXxsFontWeight": 900,
  "TypographyHeadlineStandardXxsTextTransform": "capitalize",
  "TypographySummaryFontSizeL": 20,
  "TypographySummaryFontSizeS": 16,
  "TypographySummaryFontLineHeightL": 30,
  "TypographySummaryFontLineHeightS": 24,
  "TypographySummaryStandardLFontSize": 20,
  "TypographySummaryStandardLLineHeight": 30,
  "TypographySummaryStandardLFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographySummaryStandardLFontWeight": 300,
  "TypographySummaryStandardSFontSize": 16,
  "TypographySummaryStandardSLineHeight": 24,
  "TypographySummaryStandardSFontFamily": "Retina, Helvetica, Arial, sans-serif",
  "TypographySummaryStandardSFontWeight": 300,
  "TypographyTimestampFontSizeM": 14,
  "TypographyTimestampFontLineHeightM": 22,
  "TypographyTimestampStandardMFontSize": 14,
  "TypographyTimestampStandardMLineHeight": 22,
  "TypographyTimestampStandardMFontFamily": "Retina Wide, Helvetica, Arial,sans-serif",
  "TypographyTimestampStandardMFontWeight": 300,
  "TypographyTimestampStandardMTextTransform": "uppercase",
  "BoxShadowCardDark": "0px 1px 2px 1px rgba(255, 255, 255, 0.5)",
  "BoxShadowCardLight": "0px 1px 2px 1px rgba(0, 0, 0, 0.1)",
  "BoxShadowDropdownDark": "0px 3px 7px -4px rgba(255, 255, 255, 0.5)",
  "BoxShadowDropdownLight": "0px 3px 7px -4px rgba(0, 0, 0, 0.1)"
}